import "./globals.css";
import { AuthProvider } from "@/contexts/AuthContext";
import { ReduxProvider } from "@/lib/redux/ReduxProvider";
import StatusBarSetter from "@/components/StatusBarSetter";
import SplashScreen from "@/components/SplashScreen";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="antialiased">
        <SplashScreen>
          <ReduxProvider>
            <AuthProvider>
              <StatusBarSetter />
              {children}
            </AuthProvider>
          </ReduxProvider>
        </SplashScreen>
      </body>
    </html>
  );
}
